### PR TITLE
Added French and Arabic translation

### PR DESCRIPTION
**Pull request by macro010**
Added two folders in "_locales" AR and FR, each containing a .json file with proper langue translation.

### CODE REVIEW

**Comment by pietervanheijningen** [comment]
I'm going to remove the "M" in the middleOfTheVideo arabic translation, I assume this was a mistake.
Other than that, seems fine. Thank you very much!

**Comment by pietervanheijningen** [comment]
Oh yeah, and I was not able to test it, I tried changing my chrome language to arabic, but it did not work. Hope it will work fine :D. Should do, the other languages work

**Comment by macro010** [comment]
Hey!!

Sorry for the late reply, about Arabic it's a known issue same as Chinese.
As far as i know it has something to do with how utf or encoding in general.
It was my pleasure to add something and i am happy go hear the other
languages are working just fine.

Good luch and best regards.

**Comment by pietervanheijningen** [comment]
Good to know that it works! Thanks again :)

**Pull request merged**
